const q1 = [
	{ id: 1, output: 1, text: "Montée" },
	{ id: 2, output: 2, text: "Descente" },
];

const q12 = [
	{ id: 1, output: 1, text: "Oui" },
	{ id: 2, output: 2, text: "Non" },
];


const motif = [
	{ id: 1, output: 1, text: "Votre domicile" },
	{ id: 2, output: 2, text: "Votre lieu de travail habituel" },
	{ id: 3, output: 3, text: "Un lieu de rendez-vous professionnel" },
	{ id: 4, output: 4, text: "Votre établissement scolaire, université" },
	{ id: 5, output: 5, text: "Un lieu d'achats, courses, …" },
	{ id: 6, output: 6, text: "Un rendez-vous administratif, médical" },
	{ id: 7, output: 7, text: "Un lieu de loisirs" },
	{ id: 8, output: 8, text: "Autre préciser" },
];

const mode = [
	{ id: 1, output: 1, text: "à pied exclusivement" },
	{ id: 2, output: 2, text: "en bus/car" },
	{ id: 3, output: 3, text: "en voiture conducteur" },
	{
		id: 4,
		output: 4,
		text: "en voiture passager (dans une voiture stationnée en gare - covoiturage)",
	},
	{
		id: 5,
		output: 5,
		text: "en voiture passager (dans une voiture non stationnée en gare - dépose)",
	},
	{ id: 6, output: 6, text: "en vélo" },
	{ id: 7, output: 7, text: "en deux-roues motorisés" },
	{ id: 8, output: 8, text: "en train" },
	{ id: 9, output: 9, text: "Autre : Précisez" },
];

const frequence = [
	{ id: 1, output: 1, text: "Tous les jours de la semaine" },
	{ id: 2, output: 2, text: "Tous les jours sauf le week-end" },
	{ id: 3, output: 3, text: "2/3 fois par semaine" },
	{ id: 4, output: 4, text: "1 fois par semaine" },
	{ id: 5, output: 5, text: "1 fois par mois" },
	{ id: 6, output: 6, text: "Moins d'une fois par mois" },
	{ id: 7, output: 7, text: "Rarement" },
	{ id: 8, output: 8, text: "Autre préciser" },
];

const titre = [
	{
		id: 1,
		output: 1,
		text: "Abonnement de train TER (Rémi ou Aléop)",
	},
	{ id: 2, output: 2, text: "Abonnement TGV" },
	{ id: 3, output: 3, text: "Abonnement de car Rémi" },
	{ id: 4, output: 4, text: "Abonnement de transport urbain" },
	{ id: 5, output: 5, text: "Autres abonnements" },
	{ id: 6, output: 6, text: "Billet de train Rémi (avec ou sans réduction)" },
	{
		id: 7,
		output: 7,
		text: "Billet de car Rémi (avec ou sans réduction) ou carnet de 10 voyages",
	},
	{
		id: 8,
		output: 8,
		text: "Ticket de transport urbain ou carte 10 voyages urbain",
	},
	{ id: 9, output: 9, text: "Autres titres" },
	{ id: 10, output: 10, text: "Pas de titre" },
];

const support = [
	{ id: 1, output: 1, text: "Carte billettique JVMalin" },
	{ id: 2, output: 2, text: "Support papier" },
	{ id: 3, output: 3, text: "Application/téléphone" },
	{ id: 4, output: 4, text: "Autre" },
];

const tours = [
	{id: 1,output: 3726112, text: "BEAUJARDIN"},
	{id: 2,output: 3726103, text: "CATHEDRALE"},
	{id: 3,output: 3726121, text: "LES FONTAINES"},
	{id: 4,output: 3726122, text: "DEUX LIONS GLORIETTE"},
	{id: 5,output: 3726111, text: "SANITAS-ROTONDE"},
	{id: 6,output: 3726108, text: "FEBVOTTE-MARAT"},
	{id: 7,output: 3726116, text: "PAUL BERT"},
	{id: 8,output: 3726106, text: "GIRAUDEAU"},
	{id: 9,output: 3726104, text: "LAMARTINE"},
	{id: 10,output: 3726118, text: "DOUETS MILLETIERE"},
	{id: 11,output: 3726101, text: "CENTRE"},
	{id: 12,output: 3726105, text: "RABELAIS-TONNELLE"},
	{id: 13,output: 3726113, text: "ROCHEPINARD"},
	{id: 14,output: 3726110, text: "LA FUYE VELPEAU"},
	{id: 15,output: 3726117, text: "EUROPE"},
	{id: 16,output: 3726109, text: "RIVES DU CHER"},
	{id: 17,output: 3726107, text: "LAKANAL-STRASBOURG"},
	{id: 18,output: 3726119, text: "MONTJOYEUX"},
	{id: 19,output: 3726114, text: "SAINT-SYMPHORIEN"},
	{id: 20,output: 3726115, text: "SAINTE-RADEGONDE"},
	{id: 21,output: 3726102, text: "GRAMMONT"},
	{id: 22,output: 3726120, text: "BERGEONNERIE"},
];

const orleans = [
	{id:1 , output: "La Source", text: "LA SOURCE"},
	{id:2 , output: "Est", text: "BARRIERE ST MARC - ARGONNE - FAUBOURG BOURGOGNE"},
	{id:3 , output: "Ouest", text: "DUNOIS MADELEINE"},
	{id:4 , output: "Centre ville", text: "CENTRE VILLE"},
	{id:5 , output: "Saint Marceau", text: "SAINT MARCEAU"},
	{id:6 , output: "Nord", text: "ACACIAS - BLOSSIERES - GARE"},
];

const sncf = [
	{id: 0, output: "0", text: "Arrêt Rémi"},
	{ id: 1, output: "1", text: "Ablon" },
	{ id: 2, output: "2", text: "Arpajon Accessible" },
	{ id: 3, output: "3", text: "Athis-Mons" },
	{ id: 4, output: "4", text: "Avenue du Président-Kennedy" },
	{ id: 5, output: "5", text: "Avenue Foch" },
	{ id: 6, output: "6", text: "Avenue Henri-Martin" },
	{ id: 7, output: "7", text: "Bibliothèque François-Mitterrand Accessible" },
	{ id: 8, output: "8", text: "Boulainvilliers" },
	{ id: 9, output: "9", text: "Bouray" },
	{ id: 10, output: "10", text: "Brétigny Accessible" },
	{ id: 11, output: "11", text: "Breuillet – Bruyères-le-Châtel" },
	{ id: 12, output: "12", text: "Breuillet-Village" },
	{ id: 13, output: "13", text: "Cernay Accessible" },
	{ id: 14, output: "14", text: "Chamarande" },
	{ id: 15, output: "15", text: "Champ de Mars – Tour Eiffel" },
	{ id: 16, output: "16", text: "Chaville – Vélizy Accessible" },
	{ id: 17, output: "17", text: "Chemin d'Antony" },
	{ id: 18, output: "18", text: "Choisy-le-Roi Accessible" },
	{ id: 19, output: "19", text: "Dourdan - La Forêt Accessible" },
	{ id: 20, output: "20", text: "Dourdan Accessible" },
	{ id: 21, output: "21", text: "Égly" },
	{ id: 22, output: "22", text: "Épinay-sur-Orge Accessible" },
	{ id: 23, output: "23", text: "Épinay-sur-Seine" },
	{ id: 24, output: "24", text: "Ermont – Eaubonne" },
	{ id: 25, output: "25", text: "Étampes" },
	{ id: 26, output: "26", text: "Étréchy" },
	{
		id: 27,
		output: "27",
		text: "Franconville – Le Plessis-Bouchard Accessible",
	},
	{ id: 28, output: "28", text: "Gennevilliers Accessible" },
	{
		id: 29,
		output: "29",
		text: "Hôpital européen Georges-Pompidou Accessible",
	},
	{ id: 30, output: "30", text: "Invalides" },
	{ id: 31, output: "31", text: "Issy" },
	{ id: 32, output: "32", text: "Issy-Val de Seine Accessible" },
	{ id: 33, output: "33", text: "Ivry-sur-Seine" },
	{ id: 34, output: "34", text: "Javel Accessible" },
	{ id: 35, output: "35", text: "Juvisy Accessible" },
	{ id: 36, output: "36", text: "La Norville – Saint-Germain-lès-Arpajon" },
	{ id: 37, output: "37", text: "Lardy" },
	{ id: 38, output: "38", text: "Les Ardoines" },
	{ id: 39, output: "39", text: "Les Grésillons" },
	{ id: 40, output: "40", text: "Les Saules Accessible" },
	{ id: 41, output: "41", text: "Maison de Radio France" },
	{ id: 42, output: "42", text: "Marolles-en-Hurepoix" },
	{ id: 43, output: "43", text: "Massy – Palaiseau" },
	{ id: 44, output: "44", text: "Massy – Verrières" },
	{ id: 45, output: "45", text: "Meudon-Val-Fleury Accessible" },
	{ id: 46, output: "46", text: "Montigny – Beauchamp Accessible" },
	{ id: 47, output: "47", text: "Montigny-le-Bretonneux" },
	{ id: 48, output: "48", text: "Musée d'Orsay" },
	{ id: 49, output: "49", text: "Musée du Quai Branly – Jacques-Chirac" },
	{ id: 50, output: "50", text: "Neuilly – Porte Maillot" },
	{ id: 51, output: "51", text: "Orly-Ville" },
	{ id: 52, output: "52", text: "Palais des Congrès" },
	{ id: 53, output: "53", text: "Paris-Austerlitz" },
	{ id: 54, output: "54", text: "Pereire – Levallois" },
	{ id: 55, output: "55", text: "Pierrelaye" },
	{ id: 56, output: "56", text: "Pont de l'Alma" },
	{ id: 57, output: "57", text: "Pont de Rungis – Aéroport d'Orly" },
	{ id: 58, output: "58", text: "Pont du Garigliano" },
	{ id: 59, output: "59", text: "Pontoise" },
	{ id: 60, output: "60", text: "Porchefontaine" },
	{ id: 61, output: "61", text: "Porte de Clichy" },
	{ id: 62, output: "62", text: "Rungis – La Fraternelle" },
	{ id: 63, output: "63", text: "Saint-Chéron" },
	{ id: 64, output: "64", text: "Saint-Cyr" },
	{ id: 65, output: "65", text: "Saint-Gratien Accessible" },
	{ id: 66, output: "66", text: "Saint-Martin-d'Étampes" },
	{ id: 67, output: "67", text: "Saint-Michel – Notre-Dame" },
	{ id: 68, output: "68", text: "Saint-Michel-sur-Orge Accessible" },
	{ id: 69, output: "69", text: "Saint-Ouen Accessible" },
	{ id: 70, output: "70", text: "Saint-Ouen-l'Aumône" },
	{ id: 71, output: "71", text: "Saint-Ouen-l'Aumône-Liesse Accessible" },
	{ id: 72, output: "72", text: "Saint-Quentin-en-Yvelines" },
	{ id: 73, output: "73", text: "Sainte-Geneviève-des-Bois" },
	{ id: 74, output: "74", text: "Savigny-sur-Orge" },
	{ id: 75, output: "75", text: "Sermaise" },
	{ id: 76, output: "76", text: "Tribunal de Paris" },
	{ id: 77, output: "77", text: "Valéry Giscard d'Estaing" },
	{ id: 78, output: "78", text: "Versailles-Chantiers Accessible" },
	{ id: 79, output: "79", text: "Versailles-Château-Rive-Gauche Accessible" },
	{ id: 80, output: "80", text: "Villeneuve-le-Roi" },
	{ id: 81, output: "81", text: "Viroflay-Rive-Gauche" },
	{ id: 82, output: "82", text: "Vitry-sur-Seine Accessible" },
];



export { q1, motif, mode, frequence, titre, support, tours, orleans, q12 };
